package com.haiegoo.commons.model.config;

import java.io.Serializable;

public class Enums implements Serializable {
	
	private static final long serialVersionUID = 8736853921330828202L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column enums.id
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column enums.clazz
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private String clazz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column enums.key
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private String key;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column enums.code
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private Integer code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column enums.text
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    private String text;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column enums.id
     *
     * @return the value of enums.id
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column enums.id
     *
     * @param id the value for enums.id
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column enums.clazz
     *
     * @return the value of enums.clazz
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column enums.clazz
     *
     * @param clazz the value for enums.clazz
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setClazz(String clazz) {
        this.clazz = clazz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column enums.key
     *
     * @return the value of enums.key
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column enums.key
     *
     * @param key the value for enums.key
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column enums.code
     *
     * @return the value of enums.code
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column enums.code
     *
     * @param code the value for enums.code
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column enums.text
     *
     * @return the value of enums.text
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column enums.text
     *
     * @param text the value for enums.text
     *
     * @ibatorgenerated Thu Oct 24 20:15:44 CST 2013
     */
    public void setText(String text) {
        this.text = text;
    }
}