package com.haiegoo.ucenter.model.admin;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import com.haiegoo.commons.enums.State;

public class Admin implements UserDetails, Serializable, Cloneable {
	
	private static final long serialVersionUID = -8097634475751877685L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.user_id
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.username
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String username;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.password
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.name
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.code
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.sex
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String sex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.dept
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String dept;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.position
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String position;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.mobile
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String mobile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.email
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.reg_time
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    private Date regTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column admin.state
     *
     * @ibatorgenerated Wed Jan 23 14:07:44 CST 2013
     */
    private Byte state;
    
    
    /**
     * 用户角色列表
     */
    private List<Role> roles; 
    

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column admin.user_id
     *
     * @return the value of admin.user_id
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column admin.user_id
     *
     * @param userId the value for admin.user_id
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column admin.name
     *
     * @return the value of admin.name
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column admin.name
     *
     * @param name the value for admin.name
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column admin.code
     *
     * @return the value of admin.code
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column admin.code
     *
     * @param code the value for admin.code
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column admin.sex
     *
     * @return the value of admin.sex
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column admin.sex
     *
     * @param sex the value for admin.sex
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getDept() {
		return dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column admin.position
     *
     * @return the value of admin.position
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column admin.position
     *
     * @param position the value for admin.position
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column admin.mobile
     *
     * @return the value of admin.mobile
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column admin.mobile
     *
     * @param mobile the value for admin.mobile
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column admin.email
     *
     * @return the value of admin.email
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column admin.email
     *
     * @param email the value for admin.email
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setEmail(String email) {
        this.email = email;
    }

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column admin.reg_time
     *
     * @return the value of admin.reg_time
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column admin.reg_time
     *
     * @param regTime the value for admin.reg_time
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column admin.state
     *
     * @return the value of admin.state
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column admin.state
     *
     * @param state the value for admin.state
     *
     * @ibatorgenerated Wed May 30 09:02:19 CST 2012
     */
    public void setState(Byte state) {
        this.state = state;
    }

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}
	

	@Override
	public Collection<GrantedAuthority> getAuthorities() {
		Collection<GrantedAuthority> auths = new ArrayList<GrantedAuthority>();
		
		for(Role role : this.getRoles()){
			auths.add(new SimpleGrantedAuthority(role.getType()));
		}
		
		return auths;
	}

	@Override
	public boolean isAccountNonExpired() {
		return true;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		return true;
	}

	@Override
	public boolean isEnabled() {
		if(this.state==State.ENABLE.getCode()){
			return true;
		}else{
			return false;
		}
	}

	/**
     * @return 创建并返回此对象的一个副本。
     * @throws CloneNotSupportedException
     */
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
    
}