package com.haiegoo.ucenter.model.admin;

import com.haiegoo.ucenter.service.admin.ModuleService;

import java.io.Serializable;

public class Module implements Serializable {
	
	private static final long serialVersionUID = 4101396557949370770L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module.moduleId
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    private Integer moduleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module.pid
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    private Integer pid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module.text
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    private String text;
    
    private String code;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module.url
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    private String url;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module.type
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    private String type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module.image
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    private String image;

    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column module.expanded
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    private Byte expanded;
    
    private Integer sort;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column module.moduleId
     *
     * @return the value of module.moduleId
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column module.moduleId
     *
     * @param moduleId the value for module.moduleId
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column module.pid
     *
     * @return the value of module.pid
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column module.pid
     *
     * @param pid the value for module.pid
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column module.text
     *
     * @return the value of module.text
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column module.text
     *
     * @param text the value for module.text
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public void setText(String text) {
        this.text = text;
    }

    public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column module.url
     *
     * @return the value of module.url
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column module.url
     *
     * @param url the value for module.url
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public void setUrl(String url) {
        this.url = url;
    }

    public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column module.image
     *
     * @return the value of module.image
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column module.image
     *
     * @param image the value for module.image
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public void setImage(String image) {
        this.image = image;
    }

    public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column module.expanded
     *
     * @return the value of module.expanded
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public Byte getExpanded() {
        return expanded;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column module.expanded
     *
     * @param expanded the value for module.expanded
     *
     * @ibatorgenerated Fri Oct 28 15:06:09 CST 2011
     */
    public void setExpanded(Byte expanded) {
        this.expanded = expanded;
    }

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}
	

	/**
	 * 获取模块图标
	 * @return 返回图标CSS
	 */
	public String getIconCls() {
		if(ModuleService.SYSTEM.equals(type))
			return "icon-sub-system";
		
		if(ModuleService.GROUP.equals(type))
			return "icon-module-group";
		
		if(ModuleService.MODULE.equals(type))
			return "icon-module-app";
		
		if(ModuleService.FUNCTION.equals(type))
			return "icon-module-function";
		
		return null;
	}
}