package com.haiegoo.shopping.model.product;

import java.io.Serializable;

public class Brand implements Serializable {
	
	private static final long serialVersionUID = -5871759586192755259L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column brand.id
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column brand.name
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column brand.logo
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    private String logo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column brand.url
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    private String url;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column brand.description
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column brand.seo_title
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    private String seoTitle;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column brand.seo_keywords
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    private String seoKeywords;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column brand.seo_description
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    private String seoDescription;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column brand.sort
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    private Integer sort;
    
	private Integer productCount;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column brand.id
     *
     * @return the value of brand.id
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column brand.id
     *
     * @param id the value for brand.id
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column brand.name
     *
     * @return the value of brand.name
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column brand.name
     *
     * @param name the value for brand.name
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column brand.logo
     *
     * @return the value of brand.logo
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column brand.logo
     *
     * @param logo the value for brand.logo
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column brand.url
     *
     * @return the value of brand.logo
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column brand.url
     *
     * @param logo the value for brand.logo
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column brand.description
     *
     * @return the value of brand.description
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column brand.description
     *
     * @param description the value for brand.description
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column brand.seo_title
     *
     * @return the value of brand.seo_title
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public String getSeoTitle() {
        return seoTitle;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column brand.seo_title
     *
     * @param seoTitle the value for brand.seo_title
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public void setSeoTitle(String seoTitle) {
        this.seoTitle = seoTitle;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column brand.seo_keywords
     *
     * @return the value of brand.seo_keywords
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public String getSeoKeywords() {
        return seoKeywords;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column brand.seo_keywords
     *
     * @param seoKeywords the value for brand.seo_keywords
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public void setSeoKeywords(String seoKeywords) {
        this.seoKeywords = seoKeywords;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column brand.seo_description
     *
     * @return the value of brand.seo_description
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public String getSeoDescription() {
        return seoDescription;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column brand.seo_description
     *
     * @param seoDescription the value for brand.seo_description
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public void setSeoDescription(String seoDescription) {
        this.seoDescription = seoDescription;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column brand.sort
     *
     * @return the value of brand.sort
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column brand.sort
     *
     * @param sort the value for brand.sort
     *
     * @ibatorgenerated Wed Nov 07 18:31:23 CST 2012
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

	public Integer getProductCount() {
		return productCount;
	}

	public void setProductCount(Integer productCount) {
		this.productCount = productCount;
	}
}