package com.haiegoo.shopping.model.product;

import java.io.Serializable;

public class Property implements Serializable {
	
	private static final long serialVersionUID = 1025752794086270935L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column property.id
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column property.pid
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    private Integer pid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column property.path
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    private String path;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column property.name
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column property.catePath
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    private String catePath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column property.input_type
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    private Byte inputType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column property.sort
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    private Integer sort;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column property.id
     *
     * @return the value of property.id
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column property.id
     *
     * @param id the value for property.id
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column property.pid
     *
     * @return the value of property.pid
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column property.pid
     *
     * @param pid the value for property.pid
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column property.path
     *
     * @return the value of property.path
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column property.path
     *
     * @param path the value for property.path
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column property.name
     *
     * @return the value of property.name
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column property.name
     *
     * @param name the value for property.name
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column property.catePath
     *
     * @return the value of property.catePath
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public String getCatePath() {
        return catePath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column property.catePath
     *
     * @param catePath the value for property.catePath
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public void setCatePath(String catePath) {
        this.catePath = catePath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column property.input_type
     *
     * @return the value of property.input_type
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public Byte getInputType() {
        return inputType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column property.input_type
     *
     * @param inputType the value for property.input_type
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public void setInputType(Byte inputType) {
        this.inputType = inputType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column property.sort
     *
     * @return the value of property.sort
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column property.sort
     *
     * @param sort the value for property.sort
     *
     * @ibatorgenerated Tue Apr 08 13:47:46 GMT+08:00 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}