package com.haiegoo.shopping.model.product;

import java.io.Serializable;

public class Specification implements Serializable {
	
	private static final long serialVersionUID = -7265705215899315999L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pcs_specification.id
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pcs_specification.pid
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    private Integer pid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pcs_specification.path
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    private String path;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pcs_specification.name
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pcs_specification.has_image
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    private Byte hasImage;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pcs_specification.catePath
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    private String catePath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pcs_specification.sort
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    private Integer sort;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pcs_specification.id
     *
     * @return the value of pcs_specification.id
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pcs_specification.id
     *
     * @param id the value for pcs_specification.id
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pcs_specification.pid
     *
     * @return the value of pcs_specification.pid
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pcs_specification.pid
     *
     * @param pid the value for pcs_specification.pid
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pcs_specification.path
     *
     * @return the value of pcs_specification.path
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pcs_specification.path
     *
     * @param path the value for pcs_specification.path
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pcs_specification.name
     *
     * @return the value of pcs_specification.name
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pcs_specification.name
     *
     * @param name the value for pcs_specification.name
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pcs_specification.has_image
     *
     * @return the value of pcs_specification.has_image
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public Byte getHasImage() {
        return hasImage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pcs_specification.has_image
     *
     * @param has_image the value for pcs_specification.has_image
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public void setHasImage(Byte hasImage) {
        this.hasImage = hasImage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pcs_specification.catePath
     *
     * @return the value of pcs_specification.catePath
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public String getCatePath() {
        return catePath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pcs_specification.catePath
     *
     * @param catePath the value for pcs_specification.catePath
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public void setCatePath(String catePath) {
        this.catePath = catePath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pcs_specification.sort
     *
     * @return the value of pcs_specification.sort
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pcs_specification.sort
     *
     * @param sort the value for pcs_specification.sort
     *
     * @ibatorgenerated Mon Nov 12 17:48:15 CST 2012
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
    
}