package ibatis;

public class Role {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.role_id
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    private Integer roleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.pid
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    private Integer pid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.name
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.type
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    private String type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.description
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.sort
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    private Integer sort;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.leaf
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    private Byte leaf;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.pid
     *
     * @return the value of role.pid
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.pid
     *
     * @param pid the value for role.pid
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.type
     *
     * @return the value of role.type
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.type
     *
     * @param type the value for role.type
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.description
     *
     * @return the value of role.description
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.description
     *
     * @param description the value for role.description
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.sort
     *
     * @return the value of role.sort
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.sort
     *
     * @param sort the value for role.sort
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.leaf
     *
     * @return the value of role.leaf
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public Byte getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.leaf
     *
     * @param leaf the value for role.leaf
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    public void setLeaf(Byte leaf) {
        this.leaf = leaf;
    }
}