package ibatis;

import ibatis.Role;
import ibatis.RoleExample;
import java.sql.SQLException;
import java.util.List;

public interface RoleDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    int countByExample(RoleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    int deleteByExample(RoleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    int deleteByPrimaryKey(Integer roleId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    Integer insert(Role record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    Integer insertSelective(Role record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    List selectByExample(RoleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    Role selectByPrimaryKey(Integer roleId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    int updateByExampleSelective(Role record, RoleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    int updateByExample(Role record, RoleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    int updateByPrimaryKeySelective(Role record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Sun Mar 02 14:59:23 GMT+08:00 2014
     */
    int updateByPrimaryKey(Role record) throws SQLException;
}